USE RISEJULY2025

-- TRIGGERS: IT IS AUTOMATIC REACTION OF A SQL SERVER

-- TRIGGER 1: UPDATE ----------------------------------------------
CREATE TRIGGER TrTableEmployeeForUPADATE
ON EMPTABLE
FOR UPDATE
AS
BEGIN
	PRINT 'Employee details updated!';
	SELECT * FROM deleted
	SELECT * FROM inserted
END

UPDATE EMPTABLE
SET ESALARY = 90000
WHERE EID = 101
-------------------------------------------------------------------


-- TRIGGER 2: INSERT ----------------------------------------------
CREATE TRIGGER TR_TABLE_EMPTABLE_FOR_INSERT
ON EMPTABLE
FOR INSERT
AS
BEGIN
	PRINT 'A new employee has been joined.'

	SELECT 'THIS IS INERETED TABLE'
	SELECT * FROM inserted

	SELECT 'THIS IS DELETD TABLE'
	SELECT * FROM deleted
END

INSERT INTO EMPTABLE VALUES
(116,'FAIZAN',23,200000,'FAIZAN&@GMAIL.COM','FS','INDIA')
-------------------------------------------------------------------


-- TRIGGER 3: DELETE ----------------------------------------------
CREATE TRIGGER TR_DELETE_EMP_IN_EMPTABLE
ON EMPTABLE
FOR DELETE
AS
BEGIN
	PRINT 'AN EMPLOYEE HAS BEEN DELETED!'
	SELECT * FROM deleted
END

DELETE EMPTABLE
WHERE EID = 106

SELECT * FROM EMPTABLE
-------------------------------------------------------------------


-- TRIGGER 4: AUDIT TABLE -----------------------------------------
-- CREATING TABLE
CREATE TABLE EMPLOYEE_AUDIT(
	AUDIT_ID INT IDENTITY,
	EID INT,
	OLDA_SALARY MONEY,
	NEW_SALARY MONEY,
	CHANGE_DATE DATETIME DEFAULT GETDATE()
)

SELECT * FROM EMPLOYEE_AUDIT

--delete EMPLOYEE_AUDIT

-- TRIGEGR 4.1: CREATING UPDATE TRIGGER FOR AUDIT TABLE 
CREATE TRIGGER TRG_AUDIT_SALARY_CHANGE
ON EMP5
FOR UPDATE
AS
BEGIN
	INSERT INTO EMPLOYEE_AUDIT (OLDA_SALARY,EID,NEW_SALARY)
	SELECT
		D.ESALARY AS OLDA_SALARY,
		D.EID,
		I.ESALARY AS NEW_SALARY
	FROM deleted D
	INNER JOIN inserted I
	ON D.EID = I.EID
	WHERE D.ESALARY <> I.ESALARY;
END;

--insert into table values (cl1,cl2,...),()

UPDATE EMP5
SET ESALARY = 80000
WHERE EID = 102

SELECT * FROM EMP5

SELECT * FROM EMPLOYEE_AUDIT

-- TRIGEGR 4.2: CREATING DELETE TRIGGER FOR AUDIT TABLE
--CREATE TRIGGER TRG_DELETE_ON_EMPLOYEE_AUDIT
CREATE TRIGGER TRG_DELETE_ON_EMPLOYEE_AUDIT
ON EMP5
FOR DELETE -- AFTER STORES REMAINING DATA
AS
BEGIN
	INSERT INTO EMPLOYEE_AUDIT(EID,OLDA_SALARY,CHANGE_DATE)
	SELECT EID, ESALARY,GETDATE()
	FROM deleted;
END

--DROP TRG_DELETE_ON_EMPLOYEE_AUDIT

SELECT * FROM EMPLOYEE_AUDIT

DELETE FROM EMP5
WHERE EID = 102

SELECT * FROM EMP5

INSERT INTO EMP5(EID,ENAME,EDEPARTMENT,ESALARY) VALUES
(103,'VRAJ','FS',28000)
-------------------------------------------------------------------

ALTER TRIGGER TRG_DELETE_ON_EMPLOYEE_AUDIT
ON EMP5
FOR DELETE -- FOR STORES THE ACTION DATA
AS
BEGIN
	INSERT INTO EMPLOYEE_AUDIT(EID,OLDA_SALARY,CHANGE_DATE)
	SELECT EID, ESALARY,GETDATE() FROM deleted;
END;

DELETE EMP5
WHERE EID = 5

SELECT * FROM EMPLOYEE_AUDIT

--------------------------------------------------------------------


-- TRIGGER 5: PREVENT NEGATIVE SALARY ------------------------------

CREATE TRIGGER TR_PREVENT_NEGATIVE_SALARY
ON EMP5
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (SELECT 1 FROM inserted WHERE ESALARY < 0)
	BEGIN 
		ROLLBACK TRANSACTION;
		PRINT('YOU ARE NOT ALLOWED TO ENTER THE NEGATIVE SALARY.')
	END
END

INSERT INTO EMP5(EID,ENAME,EDEPARTMENT,ESALARY) VALUES (102,'VRAJ','FS',-50000)

INSERT INTO EMP5(EID,ENAME,EDEPARTMENT,ESALARY) VALUES (102,'VRAJ','FS',50000)


SELECT * FROM EMP5

UPDATE EMP5
SET ESALARY = -60000
WHERE EID = 102;


UPDATE EMP5
SET ESALARY = 60000
WHERE EID = 102;
--------------------------------------------------------------------

-- TRIGGER 6: AUTO UPDATE ------------------------------------------
-- FIRST ADD A COLUMN FOR DATE WHEN LAST UPDATE IS DONE
ALTER TABLE EMP5 ADD LAST_MODIFIED DATE

CREATE TRIGGER TR_UPDATE_LAST_MODIFIED
ON EMP5
FOR UPDATE
AS
BEGIN
	UPDATE EMP5
	SET LAST_MODIFIED = GETDATE()
	WHERE EID IN (SELECT EID FROM inserted)
END;

--drop trigger TR_UPDATE_LAST_MODIFIED

/*
ALTER TABLE EMP5
DROP COLUMN LAST_MODIFIED
*/

UPDATE EMP5
SET ESALARY = 80000
WHERE EID = 102

----------------------------------------------------------------------

-- TRIGGER 7: INSTEAD OF TRIGGER -------------------------------------
CREATE TRIGGER TR_INSTEAD_OF_UPDATE_SALARY
ON EMP5
INSTEAD OF UPDATE
AS
BEGIN
	IF EXISTS (SELECT 1 FROM inserted I JOIN deleted D
				ON I.EID = D.EID
				WHERE I.ESALARY < D.ESALARY)
	BEGIN
		RAISERROR('ERROR: SALARY CAN NOT BE REDUCED!',16,1);
		ROLLBACK TRANSACTION;
	END;
	ELSE
	BEGIN
		-- ALLOW NORMAL UPDATE
		UPDATE EMP5
		SET ESALARY = I.ESALARY
		FROM inserted I
		WHERE EMP5.EID = I.EID
	END;
END;

UPDATE EMP5
SET ESALARY = 85000
WHERE EID = 102

SELECT * FROM EMP5

-------------------------------------------
-- INSTEAD OF TRIGGER EXAMPLE USING VIEW --
CREATE TABLE DEPARTMENT(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(50)
);

INSERT INTO DEPARTMENT VALUES
(10,'IT'),
(11,'HR')

CREATE TABLE EMPLOYEE1(
EMP_ID INT PRIMARY KEY,
NAME VARCHAR(100),
DEPT_ID INT FOREIGN KEY REFERENCES DEPARTMENT(DEPT_ID)
);

INSERT INTO EMPLOYEE1 VALUES
(101,'VRAJ',10)

-- CREATE VIEW TO JOIN THIS TWO TABLE
CREATE VIEW VW_EMPLOYEE_DEPT
AS
SELECT E.EMP_ID,E.NAME,D.DEPT_NAME
FROM EMPLOYEE1 E
JOIN DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID

SELECT * FROM VW_EMPLOYEE_DEPT
SELECT * FROM EMPLOYEE1
SELECT * FROM DEPARTMENT

select name from sys.triggers
------------------------------------------------------------------------
-- CREATE INSTEAD OF TRIGGER TO AUTO INSERT THE DATA INTO RELATED TABLES
CREATE TRIGGER TR_AUTO_INSERT_FROM_VW
ON VW_EMPLOYEE_DEPT
INSTEAD OF INSERT
AS
BEGIN
	-- INSERT NEW EMPLOYEES INTO EMPLOYEE TABLE
	INSERT INTO EMPLOYEE1 (EMP_ID,NAME,DEPT_ID)
	SELECT I.EMP_ID, I.NAME, D.DEPT_ID
	FROM inserted I JOIN DEPARTMENT D
	ON I.DEPT_NAME = D.DEPT_NAME
END;

INSERT INTO VW_EMPLOYEE_DEPT VALUES (103,'JIMIT','IT')
SELECT * FROM VW_EMPLOYEE_DEPT

SELECT * FROM EMPLOYEE1

-----------------------------------------------------------------
-- INSTEAD OF TRIGGER TO AUTO DELETE THE DATA FROM RELATED TABLES
CREATE TRIGGER TR_AUTO_DELETE_FROM_VW
ON VW_EMPLOYEE_DEPT
INSTEAD OF DELETE
AS
BEGIN
	DELETE E
	FROM EMPLOYEE1 E
	JOIN deleted D
	ON E.EMP_ID = D.EMP_ID
END;

DELETE VW_EMPLOYEE_DEPT
WHERE EMP_ID = 103

SELECT * FROM VW_EMPLOYEE_DEPT
SELECT * FROM EMPLOYEE1

------------------------------------------------------------------------
-- CREATE INSTEAD OF TRIGGER TO AUTO UPDATE THE DATA INTO RELATED TABLES
CREATE TRIGGER TR_AUTO_UPDATE_FROM_VW
ON VW_EMPLOYEE_DEPT
INSTEAD OF UPDATE
AS
BEGIN
	-- UPDATE EMPLOYEES INTO EMPLOYEE1 TABLE
	UPDATE E
	SET E.DEPT_ID = D.DEPT_ID
	FROM inserted I INNER JOIN EMPLOYEE1 E
	ON I.EMP_ID = E.EMP_ID
	INNER JOIN DEPARTMENT D
	ON I.DEPT_NAME = D.DEPT_NAME
END;

UPDATE VW_EMPLOYEE_DEPT
SET DEPT_NAME = 'HR'
WHERE EMP_ID = 102

SELECT * FROM VW_EMPLOYEE_DEPT
SELECT * FROM EMPLOYEE1

----------------------------------------------------------------------
DROP TRIGGER TrTableEmployeeForUPADATE
DROP TRIGGER TR_TABLE_EMPTABLE_FOR_INSERT
DROP TRIGGER TR_DELETE_EMP_IN_EMPTABLE
----------------------------------------------------------------------

-- TRIGGER 8: CREATE TRIGGER (RESTRICTION OF CREATING THE TABLE) -----
/*
HAS TWO TYPES:
	1. ON DATABASE
	2. ON SERVER
*/

-- TRIGGER 8.1: CREATE TRIGGER ON DATABASE
CREATE TRIGGER TR_BLOCK_TO_CREATE_NEW_TABLE
ON DATABASE
FOR CREATE_TABLE
AS
BEGIN
	PRINT 'YOU ARE NOT ALLOWED TO CREATE TABLE IN THIS DATABASE!'
	ROLLBACK TRANSACTION;
END;

CREATE TABLE NEW_TABLE (
ID INT,
NAME VARCHAR(50)
)

-- TRIGGER 8.2: CREATE TRIGGER ON SERVER
CREATE TRIGGER TR_BLOCK_TO_CREATE_NEW_TABLE
ON ALL SERVER
FOR CREATE_TABLE
AS
BEGIN
	PRINT 'YOU ARE NOT ALLOWED TO CREATE NEW TABLES IN THIS SERVER!'
	ROLLBACK TRANSACTION;
END;

CREATE TABLE NEW_TABLE (
ID INT,
NAME VARCHAR(50)
)
----------------------------------------------------------------------

-- TRIGGER 9: DROP TRIGGER -------------------------------------------
-- (USED TO RESTRICT THE USER TO DROP ANY TABLE)

-- TRIGGER 9.1: DROP TRIGGER ON DATABASE
CREATE TRIGGER TR_BLOCK_TO_DROP_TABLE
ON DATABASE
FOR DROP_TABLE
AS
BEGIN
	PRINT 'YOU ARE NOT ALLOWED TO DROP EXISTING TABLE IN DATABASE!'
	ROLLBACK TRANSACTION;
END;

DROP TABLE EMP5;

-- TRIGGER 9.2: DROP TRIGGER ON SERVER
CREATE TRIGGER TR_BLOCK_TO_DROP_TABLE
ON ALL SERVER
FOR DROP_TABLE
AS
BEGIN
	PRINT 'YOU ARE NOT ALLOWED TO DROP EXISTING TABLE IN SERVER!'
	ROLLBACK TRANSACTION;
END;

DROP TABLE EMP5;
----------------------------------------------------------------------
SELECT * FROM EMP5

SELECT NAME FROM SYS.tables WHERE TYPE = 'U'

SELECT NAME FROM SYS.triggers WHERE TYPE = 'U'

-- DROP, DISABLE, ENABLE TRIGGERS ----------------------------------------------
/*
SYNTAX:
1. DROPPING THE TRIGGER
	DROP TRIGGER TR_DELETE_EMP_IN_EMPTABLE

2. DISABLE THE TRIGGER
	DISABLE TRIGGER <TRIGGER NAME> ON <TABLE NAME>

3. ENABLE THE TRIGGER
	ENABLE TRIGGER <TRIGGER NAME> ON <TABLE NAME>
*/
DROP TRIGGER TRG_AUDIT_SALARY_CHANGE

DROP TRIGGER TRG_DELETE_ON_EMPLOYEE_AUDIT

DROP TRIGGER TR_PREVENT_NEGATIVE_SALARY

DROP TRIGGER TR_UPDATE_LAST_MODIFIED

DROP TRIGGER TR_INSTEAD_OF_UPDATE_SALARY

DROP TRIGGER TR_AUTO_INSERT_FROM_VW

DROP TRIGGER TR_AUTO_UPDATE_FROM_VW

-- ON DATABASE
DROP TRIGGER TR_BLOCK_TO_CREATE_NEW_TABLE ON ALL SERVER
-- ON SERVER
DROP TRIGGER TR_BLOCK_TO_CREATE_NEW_TABLE ON DATABASE

-- ON DATABASE
DROP TRIGGER TR_BLOCK_TO_DROP_TABLE ON DATABASE
-- ON SERVER
DROP TRIGGER TR_BLOCK_TO_DROP_TABLE ON ALL SERVER
