USE RISEJULY2025 --YOUR DB NAME

-- DATETIME :ACCEPT THE DATE AND TIME VALUES --
-- FORMAT: YYYY-MM-DD H:M:S:MS --
CREATE TABLE SQL_DAY_4(
EID INT,
ENAME VARCHAR(255),
DATE DATETIME DEFAULT GETDATE()) -- USE ONLY DATE INSTEAD A DATETIME IF YOU WANT ONLY DATE

-- GETDATE() :GIVES SYSTEM DATE AND TIME --
INSERT INTO SQL_DAY_4(EID,ENAME) VALUES
(1,'SHESHANG')

-- USE OF ONLY DATE --
INSERT INTO SQL_DAY_4 VALUES
(2,'ZALA','2025-07-20')

-- GET THE TABLE NAMES PRESENT IN THE TABLE --
SELECT NAME FROM SYS.TABLES WHERE TYPE = 'U'

-- USE OF BOTH DATE AND TIME --
INSERT INTO SQL_DAY_4 VALUES
(3,'VRAJ','2025-07-20 11:30')

-- HAVING :COLUMN WHICH HAS IS HAVING DEFINED CONDITION --
SELECT EDEPARTMENT, COUNT(*) FROM EMP5
GROUP BY EDEPARTMENT
HAVING COUNT(EID) > 1

SELECT * FROM SQL_DAY_4
-- ORDER OF SQL: --
-- SELECT
-- FROM
-- WHERE
-- GROUP BY
-- HAVING
-- ORDER BY

-- PRIMARY KEY & FOREIGN KEY --

-- CREATING PRIMARY KEY: --
-- PRIMARY KEY IS A COMBINATION OF UNIQUE + NOT NULL CONSTRAINT
-- A TABLE CAN HAVE ONLY ONE PRIMARY KEY
-- PIMARY KEY IS ORDERD IN ASCENDING ORDER BY DEFAULT

CREATE TABLE CUSTOMER(
CUS_ID INT PRIMARY KEY,
CUS_NAME VARCHAR(255),
CUS_ADDRESS VARCHAR(255),
CUS_NUMBER INT)

INSERT INTO CUSTOMER VALUES
(101, 'SHESHANG ZALAMAKAWANA','ANAND',1234),
(102, 'AKHILESH MAHESHWARI','BHILWARA',0123),
(103, 'SHESHANG ZALAMAKAWANA','ANAND',6789)

SELECT * FROM CUSTOMER
-- FOREIGN KEY: --
-- FOREIGN KEY IS USED TO ESTABLISH A RELATIONSHIP BETWEEN PARENT AND CHILD TABLE
-- IT IS USED TO MAINTAIN REFRENTIAL INTEGRITY OF DATA
-- FOREIGN KEY IS A PRIMARY KEY OF OTHER TABLE
-- VALUE OF FOREIGN KEY CAN BE NULL AND DUPLICATE

CREATE TABLE ORDERS(
ORDER_ID INT,
CUS_ID INT FOREIGN KEY REFERENCES CUSTOMER (CUS_ID),
PRODUCT_NAME VARCHAR(255),
ORDER_DATE DATETIME  DEFAULT GETDATE())

INSERT INTO ORDERS(ORDER_ID,CUS_ID,PRODUCT_NAME) VALUES
(1001,101,'MOBILE'),
(1001,102,'LAPTOP'),
(1001,103,'TABLET')

INSERT INTO ORDERS(ORDER_ID,CUS_ID,PRODUCT_NAME) VALUES
(1004,101,'MOBILE')

UPDATE ORDERS
SET ORDER_ID = 1002
WHERE CUS_ID = 102

UPDATE ORDERS
SET ORDER_ID = 1003
WHERE CUS_ID = 103


SELECT * FROM CUSTOMER
SELECT * FROM ORDERS

-- WE CAN NOT UPDATE OR DELET AN PRIMARY OR FOREIGN KEY DATA BECAUSE IT RELATIONAL TO EACHOTHER
-- BUT YOU CAN DO THIS BY USING CASCADING RULE
-- CASCADING RULE IF YOU UPDATE/DELETE FROM PARENT TABLE THAN AUTOMATICALLY 
-- THE SAME WILL BE REFLECTED IN TO THE CHIELD TABLE

ALTER TABLE ORDERS
ALTER CUS_ID INT FOREIGN KEY REFERENCES CUSTOMER (CUS_ID) ON UPDATE CASCADE ON DELETE CASCADE

ALTER TABLE ORDERS
ADD CONSTRAINT fk_orders_cus_id
FOREIGN KEY (CUS_ID)
REFERENCES CUSTOMER(CUS_ID)
ON UPDATE CASCADE
ON DELETE CASCADE;
