USE RISEJULY2025
SELECT NAME FROM SYS.tables WHERE TYPE = 'U'

SELECT * FROM CUSTOMER
SELECT * FROM ORDERS

INSERT INTO CUSTOMER VALUES
(104, 'VRAJ SHAH','VADODARA',5678),
(105, 'DIGVIJAYSINH PARMAR','KHAMBHAT',9876)

INSERT INTO ORDERS VALUES
(1004,105,'EARBUDS',2025-07-29) -- WRONG METHOD

DELETE FROM ORDERS
WHERE ORDER_ID = 1004

INSERT INTO ORDERS VALUES
(1004,105,'EARBUDS','2025-07-29') -- CORRECTED METHOD

SELECT * FROM ORDERS


-- JOINS --
-- INNER JOIN
SELECT * FROM CUSTOMER C
INNER JOIN ORDERS O
ON C.CUS_ID = O.CUS_ID

-- LEFT JOIN
SELECT * FROM CUSTOMER C
LEFT JOIN ORDERS O
ON C.CUS_ID = O.CUS_ID

-- RIGHT JOIN
SELECT * FROM CUSTOMER C
RIGHT JOIN ORDERS O
ON C.CUS_ID = O.CUS_ID

-- FULL JOIN
SELECT * FROM CUSTOMER C
FULL JOIN ORDERS O
ON C.CUS_ID = O.CUS_ID

-- LEFT EXCLUSIVE JOIN
SELECT * FROM CUSTOMER C
LEFT JOIN ORDERS O
ON C.CUS_ID = O.CUS_ID
WHERE O.CUS_ID IS NULL

-- RIGHT EXCLUSIVE JOIN
SELECT * FROM CUSTOMER C
RIGHT JOIN ORDERS O
ON C.CUS_ID = O.CUS_ID
WHERE C.CUS_ID IS NULL

-- FULL EXCLUSIVE JOIN
SELECT * FROM CUSTOMER C
FULL JOIN ORDERS O
ON C.CUS_ID = O.CUS_ID
WHERE C.CUS_ID IS NULL AND O.CUS_ID IS NULL



SELECT * FROM CUSTOMER
SELECT * FROM ORDERS
-- CROSS JOIN