USE RISEJULY2025
-- GET THE TABLE NAMES PRESENT IN THE TABLE --
SELECT NAME FROM SYS.TABLES WHERE TYPE = 'U'

-- IDENTITY :ADD INCREMENTAL VALUES --

CREATE TABLE EMP1
(EID INT IDENTITY,
ENAME VARCHAR(255))

INSERT EMP1 VALUES
('SUREHS')
SELECT * FROM EMP1

INSERT EMP1 VALUES
('SUREHS')
SELECT * FROM EMP1

INSERT EMP1 VALUES ('MAHESH')
SELECT * FROM EMP1

INSERT EMP1 VALUES (5,'RAMESH')
SELECT * FROM EMP1

SET IDENTITY_INSERT EMP1 ON

INSERT EMP1 (EID,ENAME) VALUES 
(5,'RAMESH')
SELECT * FROM EMP1


-- CHECK :ADD CONDITION TO FULL FILL --
CREATE TABLE EMP2
(EID INT IDENTITY(101,1),
ENAME VARCHAR(255),
SALARY DECIMAL (8,2) CHECK (SALARY > 2000))

INSERT EMP2 VALUES
('SURESH',3000)
SELECT * FROM EMP2

INSERT EMP2 VALUES
('MAHESH',1000)

ALTER TABLE EMP2
ADD EAGE INT CHECK (EAGE >= 18)
SELECT * FROM EMP2

INSERT EMP2 VALUES ('MAHESH',5000,18)
SELECT * FROM EMP2

ALTER TABLE EMP2
ADD CONSTRAINT EAGE CHECK (EAGE >= 18 AND EAGE <= 60)
SELECT * FROM EMP2

INSERT EMP2 VALUES ('SHESHANG',50000, 65)


-- DEFAULT :ADD DEFAULT VALUES --
CREATE TABLE EMP3
(EID INT IDENTITY(1001,2),
ENAME VARCHAR(255),
STATUS VARCHAR(255) DEFAULT 'ACTIVATE')

INSERT EMP3(ENAME) VALUES
('SURESH')
SELECT * FROM EMP3

INSERT EMP3(ENAME,STATUS) VALUES
('MAHESH','NOTICE')
SELECT * FROM EMP3

-- NOT NULL :ADDED VALUES SHOULD NOT BE NULL --
ALTER TABLE EMP3
ADD EMAIL VARCHAR(255) NOT NULL

CREATE TABLE EMP4
(EID INT IDENTITY(1001,2),
ENAME VARCHAR(255),
EMAIL VARCHAR(255) NOT NULL)

SELECT * FROM EMP4

INSERT INTO EMP4(ENAME) VALUES ('ZALA') -- WILL GIVE ERROR

INSERT INTO EMP4(ENAME,EMAIL) VALUES
('ZALA','ZALA@ABC.COM')

SELECT * FROM EMP4

-- UNIQUE : ADDED VALUES WILL BE UNIQUE --

ALTER TABLE EMP4
ADD BLOUD_GROUP VARCHAR(255) UNIQUE

INSERT INTO EMP4 (ENAME,EMAIL,BLOUD_GROUP) VALUES
('SHESHANG','SHESHANG@ABC.COM','O+')

INSERT INTO EMP4 (ENAME,EMAIL,BLOUD_GROUP) VALUES
('VRAJ','VRAJ@ABC.COM','B+')

SELECT * FROM EMP4

-- UNIQUE AND NOT NULL : ADD UNIQUE AND NOT NULL VALUES
DROP TABLE EMP4

CREATE TABLE EMP4
(EID INT IDENTITY(1001,2),
ENAME VARCHAR(255),
EMAIL VARCHAR(255) NOT NULL UNIQUE)

INSERT INTO EMP4 (ENAME,EMAIL) VALUES
('ZALA','ZALA@ABC.COM'),
('SHESHANG','ZALA@ABC.COM') -- THIS WILL GIVE ERROR

INSERT INTO EMP4 (ENAME,EMAIL) VALUES
('ZALA','ZALA@ABC.COM'),
('SHESHANG','SHESHANG@ABC.COM')

-- AGGREGATE FUNCTIONS: COUNT, SUM, MIN, MAX
CREATE TABLE EMP5
(EID INT,
ENAME VARCHAR(255),
EDEPARTMENT VARCHAR(255),
ESALARY MONEY)

INSERT INTO EMP5 VALUES
(1,'ZALA','FS',50000),
(2,'SHESHANG','QA',50000),
(3,'MIHIR','DA',50000),
(4,'HARDIK','DE',50000),
(5,'DIGVIJAY','JD',50000),
(6,'VRAJ','PD',50000),
(7,'RUSHABH','FS',50000)

-- COUNT :TOTAL  NUMBERS --
SELECT COUNT(EID) AS 'TOTAL EMPLOYEES' FROM EMP5

-- SUM :ADDITION OF VALUES --
SELECT SUM(ESALARY) FROM EMP5

-- MAX :MAXIMUM NUMBER IN GROUP OR COLUMN
SELECT MAX(ESALARY) FROM EMP5

-- MIN :MINIMUM NUMBER IN GROUP OR COLUMN
SELECT MIN(ESALARY) FROM EMP5

-- DISTINCT :DISTINCT VALUES IN GROUP OR COLUMN
SELECT COUNT(DISTINCT EDEPARTMENT) FROM EMP5


-- 1. Find out how many employees are in each department.
SELECT EDEPARTMENT, COUNT(EID) AS TOTAL_EMP
FROM EMP5
GROUP BY EDEPARTMENT

-- 2. Calculate the average salary for employees in each department.
SELECT EDEPARTMENT, AVG(ESALARY) AS TOTAL_EMP
FROM EMP5
GROUP BY EDEPARTMENT

-- 3. Find the total quantity sold for each distinct product.
SELECT product_name, COUNT(QUANTITY) FROM SALES
GROUP BY product_name

-- 4. Maximum Price of a Product in each region.
SELECT region,MAX(PRICE) FROM SALES 
GROUP BY region

-- 5. Minimum and maximum salary per department.
SELECT EDEPARTMENT, MAX(ESALARY) AS MAX_SALARY, MIN(ESALARY) AS MIN_SALARY FROM EMP5
GROUP BY EDEPARTMENT

-- 6. Total Sales values per region.
SELECT REGION, SUM(price*quantity) AS TOTAL_SALES FROM sales
GROUP BY REGION

SELECT * FROM SALES