USE RISEJULY2025

CREATE TABLE STUDENT (
	STD_ID INT,
	STD_NAME VARCHAR(50),
	STD_STANDARD INT,
	STD_STREAM VARCHAR(20),
	STD_PERCENTAGE INT
)

SELECT * FROM STUDENT

INSERT INTO STUDENT VALUES
	(101,'SHESHANG ZALAMAKWANA',12,'SCIENCE',81),
	(102,'DIGVIJAY PARMAR',11,'SCIENCE',70)

INSERT INTO STUDENT(STD_ID,STD_NAME,STD_STANDARD,STD_PERCENTAGE) 
VALUES
(103, 'VRAJ SHAH', 10, 60),
(104,'RUSHBH KAUSALYA',9,99),
(105, 'SHESHANG',10,11)

UPDATE STUDENT
SET STD_STANDARD = '12', STD_STREAM = 'COMMERCE', STD_PERCENTAGE = 100
WHERE STD_ID = 105

ALTER TABLE STUDENT
ADD STD_AGE INT

UPDATE STUDENT
SET STD_AGE = 20

ALTER TABLE STUDENT
ALTER COLUMN STD_AGE VARCHAR(50)

UPDATE STUDENT
SET STD_AGE = 'RISE JULY 2025'

SP_RENAME 'STUDENT.STD_AGE', 'STD_SCHOOL'

DELETE FROM STUDENT
WHERE STD_ID = 103 AND STD_STREAM IS NULL

DELETE FROM STUDENT
WHERE STD_ID = 104 AND STD_STREAM IS NULL

DELETE FROM STUDENT
WHERE STD_ID = 105 AND STD_STREAM IS NULL


DELETE FROM STUDENT
WHERE STD_ID BETWEEN 103 AND 105

SELECT * FROM STUDENT
ORDER BY STD_ID
SELECT TOP 2 * FROM STUDENT