USE RISEJULY2025
-- VIEW

-- VIEW :VIEW IS USED TO SHOW LIMITED DATA TO PREVENT CONFIDENTIAL DATA
-- CREATE SYNTAX :CREATE VIEW <VIEW NAME> AS <YOUR LIMITED QUERY>
CREATE VIEW STUDENT_AND_COURSE
AS
SELECT S.SNAME, C.CNAME FROM STD S
JOIN COURSE C
ON S.CID = C.CID

SELECT * FROM STUDENT_AND_COURSE

-- ALTER SYNTAX : ALTER VIEW <VIEW NAME> AS <YOUR SAME QUERY USED IN VIEW>
ALTER VIEW STUDENT_AND_COURSE
AS
SELECT S.STUDENT_ID,S.SNAME, C.CNAME FROM STD S
JOIN COURSE C
ON S.CID = C.CID

SELECT * FROM STUDENT_AND_COURSE

-- DROP SYNTAX :DROP VIEW <VIEW NAME>
DROP VIEW STUDENT_AND_COURSE

-- WE CAN UPDATE THE DATA IN VIEW WHICH WILL DIRECTLY AFFECT THE ACTUAL DATA
-- AND IF WE CHANGE THE ACTUAL DATA THE VIEW DATA WILL ASLO GET AFFECTED
-- FOR EXAMPLE ALTER COLUMN NAME IN TABLE, UPDATE VALUES IN TABLE OR VIEW ETC.
