-- NON ANSI JOINS --
-- EQUI JOINS '='
SELECT * FROM Bank_Surat
SELECT * FROM Bank_Vadodara

SELECT * FROM Bank_Surat S, Bank_Vadodara V
WHERE S.Bank_Id = V.Bank_Id

-- NON EQUI JOINS '<','>','<=','>=', '<>'
INSERT INTO Bank_Vadodara VALUES
(104,'ICICI','AKOTA'),
(105,'AXIS','MANEJA')

SELECT * FROM Bank_Surat S, Bank_Vadodara V
WHERE S.Bank_Id > V.Bank_Id

SELECT * FROM Bank_Surat S, Bank_Vadodara V
WHERE S.Bank_Id < V.Bank_Id

SELECT * FROM Bank_Surat S, Bank_Vadodara V
WHERE S.Bank_Id >= V.Bank_Id

SELECT * FROM Bank_Surat S, Bank_Vadodara V
WHERE S.Bank_Id <= V.Bank_Id

SELECT * FROM Bank_Surat S, Bank_Vadodara V
WHERE S.Bank_Id <> V.Bank_Id


-- NATURAL JOIN
-- NOTE SUPPORTED IN SQL SERVER
/*
SELECT * FROM COURSE
NATURAL JOIN STD
*/

-- SELF JOIN --
-- 
SELECT E1.ENAME, E1.EID, E2.ESALARY FROM EMPTABLE E1
JOIN EMPTABLE E2
ON E1.ESALARY = E2.ESALARY AND E1.EID <> E2.EID
ORDER BY E1.ESALARY DESC

SELECT * FROM EMPTABLE
ORDER BY ESALARY

SELECT E1.PRODUCT_NAME, E1.QUANTITY, E2.PRICE FROM SALES E1
JOIN SALES E2
ON E1.QUANTITY = E2.QUANTITY AND E1.PRODUCT_ID <> E2.PRODUCT_ID
ORDER BY E1.QUANTITY DESC

SELECT * FROM SALES
