USE RISEJULY2025

-- SUBQUERY (NESTED QUERY)
-- SELECT * FROM <TABK_NAME_1> = (SELECT*FROM <TABLE_NAME_1>)

-- QUERY TO FIND THE MAXIMUM SALARY WITHOUT USING SUB QUERY
SELECT * FROM EMP5

UPDATE EMP5
SET ESALARY = 25000
WHERE EDEPARTMENT = 'JD' OR EDEPARTMENT = 'PD'

-- AND USING SUB QUERY
SELECT * FROM EMP5 ORDER BY ESALARY DESC
SELECT ENAME, ESALARY FROM EMP5
WHERE ESALARY = (SELECT MAX(DISTINCT ESALARY) FROM EMP5)

-- ANOTHER METHOD --
SELECT DISTINCT ESALARY FROM EMP5
ORDER BY ESALARY DESC
OFFSET 1 ROW --SKIP 1 ROW
FETCH NEXT 1 ROW ONLY

-- 
SELECT ENAME, ESALARY FROM EMP5
WHERE ESALARY<(SELECT MAX( ESALARY) FROM EMP5)

--
SELECT ENAME, ESALARY FROM EMP5
WHERE ESALARY = (SELECT MAX( ESALARY) FROM EMP5
					WHERE ESALARY < (SELECT MAX(ESALARY) FROM EMP5))

--
SELECT ENAME, ESALARY
FROM EMP5
WHERE ESALARY IN (
    (SELECT MAX(ESALARY) FROM EMP5)
    UNION
    (SELECT MIN(ESALARY) FROM EMP5)
)

-- 
SELECT * FROM EMP5
SELECT ENAME, EDEPARTMENT FROM EMP5
WHERE EDEPARTMENT IN
    (SELECT EDEPARTMENT FROM EMP5 
    WHERE ENAME IN ('ZALA','VRAJ'))