USE RISEJULY2025

SELECT NAME FROM SYS.TABLES WHERE TYPE = 'U'

SELECT * FROM CUSTOMER
SELECT * FROM ORDERS


CREATE TABLE STD(
STUDENT_ID INT,
SNAME VARCHAR(255),
BATCH VARCHAR(255),
CID INT
)


INSERT INTO STD VALUES
(101,'SHESHANG','JULY2025',10),
(102,'AKHILESH','JAN2025',20),
(103,'VRAJ','JULY2925',30)

CREATE TABLE COURSE(
CID INT,
CNAME VARCHAR(255),
CFEE MONEY
)

INSERT INTO COURSE VALUES
(10,'FullStack',10000),
(20,'QA',10000),
(30,'Data Scienc',10000),
(40,'Data Analysis',10000),
(50,'Data Engineering',10000)


-- JOINS --
-- COMBINING MORE THAN 1 TABLE
-- ANSI = ON & NON ANSI = WHRE (EQI = AND NON EQI <> OR != JOINS)
-- DATA TYPE AND VALUES SHOULD BE SAME IN BOTH COLUMNS TO JOIN BOTH TABLES
-- IT MUST HAVE SAME COLUMNS IN BOTH TABLES TO JOIN THE TABLES



-- INNER JOIN --
-- COMMEN VALUES IN TWO TABLES
/* SYNTAX :
SELECT COL_NAME 
FROM TABLE_A
JOIN TABLE_B
ON TABLE_A.COL_NAME = TABLE_B.COL_NAME
*/

SELECT *
FROM STD S
INNER JOIN COURSE C
ON S.CID = C.CID

SELECT * FROM STD
SELECT * FROM COURSE



-- LEFT JOIN --
-- GIVES MATCHING COLUMN IN BOTH TABLE AND ALL THE COLUMNS OF LEFT TABLE ONLY
/*
SELECT COL_NAME
FROM TABLE_A
LEFT JOIN TABLE_B
ON TABLE_A.COL_NAME = TABLE_B.COL_NAME
*/
SELECT *
FROM STD S
LEFT JOIN COURSE C
ON S.CID = C.CID



-- RIGHT JOIN --
-- GIVES MATCHING COLUMN IN BOTH TABLE AND ALL THE COLUMNS OF RIGHT TABLE ONLY
/*
SELECT COL_NAME
FROM TABLE_A
RIGHT JOIN TABLE_B
ON TABLE_A.COL_NAME = TABLE_B.COL_NAME
*/
SELECT *
FROM STD S
RIGHT JOIN COURSE C
ON S.CID = C.CID



-- FULL JOIN --
-- INNER + LEFT + RIGHT
/*
SELECT * FROM TABLE_A
FULL JOIN TABLE_B
ON TABLE_A.COLUMN = TABLE_B.COLUMN
*/
SELECT *
FROM STD S
FULL JOIN COURSE C
ON S.CID = C.CID



-- LEFT EX-CLUSIVE JOIN --
/* 
SELECT * FROM TABLE_A
LEFT JOIN TABLE_B
ON TABLE_A.COLUMN = TABLE_B.COLUMN
WHERE TABLE_B.COLUMN IS NULL
*/
SELECT *
FROM COURSE C
LEFT JOIN STD S
ON C.CID = S.CID
WHERE S.CID IS NULL


SELECT * FROM COURSE
SELECT * FROM STD


-- RIGHT EX-CLUSIVE JOIN --
/* 
SELECT * FROM TABLE_A
RIGHT JOIN TABLE_B
ON TABLE_A.COLUMN = TABLE_B.COLUMN
WHERE TABLE_A.COLUMN IS NULL
*/
SELECT *
FROM STD S
RIGHT JOIN COURSE C
ON C.CID = S.CID
WHERE S.CID IS NULL




-- FULL EX-CLUSIVE JOIN OR OUTER JOIN--
/* 
SELECT * FROM TABLE_A
RIGHT JOIN TABLE_B
ON TABLE_A.COLUMN = TABLE_B.COLUMN
WHERE TABLE_A.COLUMN IS NULL OR TABLE_B.COLUMN IS NULL
*/



-- CROSS JOIN --
SELECT * FROM COURSE
CROSS JOIN STD

SELECT * FROM COURSE
SELECT * FROM STD
