-- CREATE AND USE DATABASE --
create database RISEJULY
use RISEJULY

-- CHANGE THE NAME OF DATABASE --
Alter database RISEJULY 
MODIFY NAME = RISEJULY2025

-- DROP DATABASE--
DROP DATABASE RISEJULY2025

-- CREATE DATABSE 
create database RISEJULY2025

-- USE DATABASE TO CREATE TABLES --
use RISEJULY2025

-- CREATE TABLE --
CREATE TABLE EMPLOYEE (
	EID INT,
	ENAME VARCHAR(20),
	EAGE INT,
	SALARY MONEY -- INSTEAD "MONEY" WE CAN USE "DECIMAL(TOTAL DIGIT, DECIMAL PLACES)"
)

-- VISUALIZE THE TABLE --
SELECT * FROM EMPLOYEE

-- INSERT THE RECORDS IN THE TABLE --
-- METHOD 1 --
INSERT INTO EMPLOYEE VALUES(101,'SHESHANG ZALAMAKWANA',23,50000)
-- METHOD 2 --
INSERT INTO EMPLOYEE (EID, ENAME, EAGE)
VALUES(102, 'MONALI ZALAMAKWANA' , 25)
-- METHOD 3 --
INSERT EMPLOYEE VALUES
(103, 'DIGVIJAY', 23, 25000),
(104, 'VRAJ', 21, 25000),
(105, 'RUSHABH', 20, 25000)

-- UPDATE --
-- METHOD 1 --
UPDATE EMPLOYEE
SET SALARY = 60000
WHERE EID = 105

-- METHOD 2 --
UPDATE EMPLOYEE 
SET SALARY = 20000
WHERE SALARY IS NULL

-- METHOD 3 --
/*
UPDATE EMPLOYEE
SET SALARY = 30000 -- UPDATE WHOLE COLUMN WITH SAME VALUE --
*/

-- ADD COLUMN IN TABLE AFTER CREATION --
ALTER TABLE EMPLOYEE
ADD EMAILID VARCHAR(255)

-- DROP EXISTING COLUMN IN THE TABLE --
ALTER TABLE EMPLOYEE
DROP COLUMN EMAILID

-- CHANGE OR UPDATE DATATYPES OF THE TABLE --
ALTER TABLE EMPLOYEE
ALTER COLUMN ENAME VARCHAR(10)

-- CHANGE TABLE NAME --
SP_RENAME 'EMPLOYEE' , 'EMPTABLE'

-- CHANGE COLUMN NAME --
SP_RENAME 'EMPTABLE.SALARY' , 'ESALARY'

-- DELETE --
-- METHOD 1 --
DELETE FROM EMPTABLE
WHERE EID = 1

-- METHOD 2 --
DELETE FROM EMPTABLE
WHERE ESALARY IS NULL

-- METHOD 3 --
/*
DELETE FROM EMPTABLE -- DELET ALL THE ROWS IN THE DATABASE --
*/

-- METHOD 4 --
-- WILL LERN LATER BUT JUST TRING ANOTHER WAY OF DELETING FIRST 4 ROWS IN TABLE --
WITH CTE AS (
    SELECT TOP 4*
    FROM EMPTABLE
    ORDER BY EID
)
DELETE FROM CTE;

---------
-- ORDER ROW IN ASCENDING ORER
SELECT * FROM EMPTABLE
ORDER BY EID ASC

-- ORDER ROW IN DECENDING ORDER
SELECT * FROM EMPTABLE
ORDER BY EID DESC

/*
DDL - CREATE, ALTER, DROP (ENTIRE TABLE WILL DELETE)
DML - UPDATE, ALTER , DELETE (PERTICULER RECORD)
*/