USE RISEJULY2025

SELECT NAME FROM SYS.tables
-- QUERY OPTIMIZATION
-- UPDATE WITH IF EXISTS
IF EXISTS (SELECT 1 FROM EMP5 WHERE EID = 5)
BEGIN
	UPDATE EMP5
	SET ESALARY = 50000
	WHERE EID = 5;
	PRINT 'EMPLOYEE UPDATE SUCCESSUFULL!'
END
ELSE
	PRINT 'EMPLOYEE DOES NOT EXIST WITH EID=5'


-- DELETE WITH IF EXISTS
IF EXISTS (SELECT 1 FROM EMP5 WHERE EID = 5)
BEGIN
	DELETE FROM EMP5
	WHERE EID = 5;
	PRINT 'EMPLOYEE DELETED SUCCESFULLY!'
END
ELSE
	PRINT 'EMPLOYEE DOES NOT EXIST WITH EID=5'

-- USING IF EXISTS FOR INSERT
IF NOT EXISTS (SELECT 1 FROM EMPTABLE WHERE EID = 101)
BEGIN
	INSERT INTO EMPTABLE (EID, ENAME, ESALARY)
	VALUES(101,'RAMESH',50000);
	PRINT 'EMPLOYEE INSERTED SUCCESFULLY'
END
ELSE
	PRINT 'EMPLOYEE ALREADY THERE IN TABLE'

/*
ISNULL():
- USED AS TEMPORARY REPLACEMENT OF NULL VALUES
- SYNTAX: ISNULL(COLUMN_NAME,REPLACEMENT_VALUE)
- EXAMPLE: ISNULL(FEES_PAID,PENDING)
*/
SELECT EID, ENAME, ISNULL(EMAIL_ID,'PANDING') FROM  EMPTABLE;


/*
CTE (COMMON TABLE EXPRESSION): TEMPORARY RESULT SET
- IT DOES NOT EXIST ALONE.
- IT ALWAYS RUNS WITH SELECT QUERY MENTIONED AFTER IT.
- USED FOR FAST REUSABILITY IN BIG SQL QUERIES.
*/ 
WITH HighSalaryEmployees AS(
	SELECT *
	FROM EMPTABLE
	WHERE ESALARY > 50000
)
SELECT EID, ENAME, ESALARY FROM HighSalaryEmployees;


SELECT * FROM EMP5
